Accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = "Accounts"
urlpatterns = [
    path('register/',views.register_user, name='register_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/',views.logout_user, name='logout_user')
]

Elibrary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #add include to your apps url.py
    path('',include('ReadBook.urls')),
    path('',include('Payment.urls')),
    path('',include('Search.urls')),
    path('', include('Accounts.urls')),
    path('api/',include('GET_API.urls')),
    path('api/',include('DELETE_API.urls')),
    path('api/',include('PUT_API.urls')),
    path('api/',include('POST_API.urls')),
    path('api/',include('PostBook_POST_API.urls')),
]

Payment/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'Payment'

urlpatterns = [
	path('getbook/<int:id>', views.getBook, name= 'getBook'),
	path('payment/<int:bid>', views.payment, name ='Payment'),
	path('updateamount/', views.update_amount, name ='updateamount'),
]

ReadBook/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ReadBook"

urlpatterns = [
    path('', views.loadBook, name='premiumbook'),
    path('description/<int:bid>/', views.bookDescription, name='description'),
    path('addbook/', views.addBook, name='addbook'),
    path('review/<int:bid>/', views.review, name="review"),
    path('rating/<int:bid>/', views.rating, name='rating'),
    path('delete/<int:bid>/',views.deleteBook, name='deletebook'),
    path('update/<int:bid>/',views.updateBook, name='updateBook'),
    path('download/<int:bid>/',views.download, name='download'),
    path('mybooks/',views.booksOwn, name='mybooks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= 'Search'
urlpatterns = [
	path('search/', views.search, name='search'),
]

templates/Base/Header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Read Book</title>

    <!-- jquery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Compiled and minified CSS materialized -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <!-- CDN for Icon -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- Compiled and minified JavaScript for materialized -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- individaul css -->
    <link rel="stylesheet" href="{% static 'Payment/transaction.css' %}" />
    <link rel="stylesheet" href="{% static 'ReadBook/Rating.css' %}" />
    <link rel="stylesheet" href="{% static 'ReadBook/style.css' %}" />

    <!-- individaul Javascript/Jquery -->
    <script src="{% static 'ReadBook/alert.js' %}"></script>
  </head>

  <body>
    {% include "./Navbar.html" %}
    <div class="container">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

templates/Base/Navbar.html
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content" style="height:0px;">
  {% if request.user.is_authenticated %}
  <li><a href="{% url 'Payment:updateamount' %}" style="padding-right: 0px;">Add Balance</a></li>
  <li><a href="{% url 'Accounts:logout_user' %}">Logout</a></li>
  {% else %}
  <li><a href="{% url 'Accounts:login_user' %}">Login</a></li>
  <li><a href="{% url 'Accounts:register_user' %}">Register</a></li>
  {% endif %}
</ul>
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo" style="margin-left: 60px;">E-Library</a>
    <ul class="right hide-on-med-and-down" style="height: 0px;">
      {% if request.user.is_authenticated %}
      <li>
        <a href="{% url 'ReadBook:mybooks' %}"><i class="material-icons" style="display: inline; vertical-align: bottom;">book</i>My Books</a>
      </li>
      <li>
        <a href="{% url 'ReadBook:addbook' %}"><i class="material-icons" style="display: inline; vertical-align: bottom;">add</i>AddBook</a><br />
      </li>
      {% if amount %}
      <li>
        <span style="font-weight: 501;border: 1px solid;padding: 5px;border-radius: 3px;vertical-align: sub;margin: 5px;">
          <i class="material-icons" style="display: inline;vertical-align: bottom;">account_balance_wallet</i> ${{amount}}
        </span>
      </li>
      {% endif %} {% else %}
      <li><a href="/admin/" style="font-weight: 501;">Admin</a><br /></li>
      {% endif %}
      <!-- Dropdown Trigger -->
      <li>
        <a class="dropdown-trigger" href="#!" data-target="dropdown1">
          <span style="font-weight: 501;">
            <i class="material-icons" style="display: inline; vertical-align: bottom;">account_circle</i>
            {{request.user.is_authenticated|yesno:',Login'}}{% firstof request.user.username|title %}
            <i class="material-icons right" style="margin-left: 0px;">arrow_drop_down </i>
          </span>
        </a>
      </li>
    </ul>
  </div>
</nav>
<nav style="width: 500px; margin-top: -65px; margin-left: 380px; margin-bottom: 20px;">
  <div class="nav-wrapper" style="width: 500px; ">
    <form method="GET" action='{% url "Search:search" %}'>
      <div class="input-field">
        <input id="search" type="search" name="q" placeholder="Search" />
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>
  </div>
</nav>
<script type="text/javascript">
  $(document).ready(function() {
    $(".dropdown-trigger").dropdown();
  });
</script>