Elibrary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #add include to your apps url.py
    path('',include('ReadBook.urls')),
    path('',include('Payment.urls')),
    path('',include('Search.urls')),
    path('', include('Accounts.urls')),
    path('api/',include('GET_API.urls')),
    path('api/',include('DELETE_API.urls')),
    path('api/',include('PUT_API.urls')),
    path('api/',include('POST_API.urls')),
    path('api/',include('PostBook_POST_API.urls')),
]

Payment/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'Payment'

urlpatterns = [
	path('getbook/<int:id>', views.getBook, name= 'getBook'),
	path('payment/<int:bid>', views.payment, name ='Payment'),
	path('updateamount/', views.update_amount, name ='updateamount'),
]

ReadBook/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ReadBook"

urlpatterns = [
    path('', views.loadBook, name='premiumbook'),
    path('description/<int:bid>/', views.bookDescription, name='description'),
    path('addbook/', views.addBook, name='addbook'),
    path('review/<int:bid>/', views.review, name="review"),
    path('rating/<int:bid>/', views.rating, name='rating'),
    path('delete/<int:bid>/',views.deleteBook, name='deletebook'),
    path('update/<int:bid>/',views.updateBook, name='updateBook'),
    path('download/<int:bid>/',views.download, name='download'),
    path('mybooks/',views.booksOwn, name='mybooks'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= 'Search'
urlpatterns = [
	path('search/', views.search, name='search'),
]

ReadBook/models.py
from django.db import models
from django.contrib.auth.models import User
import os
# Create your models here.


class UserInfo(models.Model):
    # linking to user model through one to one relation
    users = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    user_type = models.CharField(max_length=6)
    user_amount = models.IntegerField(default=0)

    def __str__(self):
        return self.users.username
    
    #Test Case
    def validate_UserInfo(self):
        return self.user_amount > 0 and (self.user_type == "Author" or self.user_type == "Reader")

class Book(models.Model):
    book_name = models.CharField(max_length=50)
    uploaded_by = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    book_price = models.IntegerField(default=0)
    book_type = models.CharField(max_length=10)
    book_discount = models.IntegerField(default=0)
    book_cover = models.ImageField(upload_to='book_images/')
    book_description = models.TextField()
    book_category = models.CharField(max_length=30)
    book_file = models.FileField(upload_to='book/')
    book_rating = models.SmallIntegerField(default=0)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.book_name)

    #overriding delete method
    def delete(self, *args, **kwargs):
        self.book_file.delete()
        self.book_cover.delete()
        super().delete(*args, **kwargs)  # Call the "real" delete() method.
    
    #Test Case
    def check_uploaded_file(self):
        return os.path.exists(self.book_file.path) and os.path.exists(self.book_cover.path)
    
    #Test Case
    def validate_book_rating(self):
        return  self.book_rating >= 0 or self.book_rating <=5


class Transaction(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    price = models.IntegerField(null=False)
    discount = models.IntegerField(default=0)
    total = models.IntegerField()

    def __str__(self):
        return str(self.book) + " ==> " + str(self.user)

    #Test Case
    def validate_transaction_total(self):
        return self.price - self.discount

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)
    review = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.book) + " - " + str(self.user) + " - " + str(self.rating)
    
    #Test Case
    def validate_rewiew_count(self):
        count = Review.objects.filter(user = self.user).count()
        return count == 1

    #Test Case
    def validate_user_rating(self):
        return  self.rating >= 0 or self.rating <= 5
    

ReadBook/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.http import HttpResponse
from .models import Book,Review,Transaction,UserInfo
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.contrib import messages

from .decorator import author_only

# Create your views here.
def loadBook(request):
  '''
    This view function will load all the books.
  '''
  books = Book.objects.all()
  amount = UserInfo.objects.get(pk = request.user.id).user_amount if request.user.is_authenticated else None 
  return render(request,'ReadBook/Book.html',context={'books':books,'amount':amount})

def bookDescription(request,bid):
  '''
    This view function will handle a book description page.
  '''
  book = None
  reviews = None
  bought = False
  hadreview = None
  owner = False
  amount = None
  loggedin = True if request.user.is_authenticated else False 
  
  if Book.objects.filter(id=bid).exists():
    try:
      book = Book.objects.get(id=bid)
      reviews = Review.objects.filter(book_id = bid).order_by('date').all()[:5]
      if loggedin:
        #get user amount
        amount = UserInfo.objects.get(pk = request.user.id).user_amount
        #check owner
        owner = True if Book.objects.get(pk = bid).uploaded_by_id == request.user.id else False
        if not owner:
          #check if user have bought this book 
          bought = True if Transaction.objects.filter(user_id=request.user.id,book_id=bid).exists() else Book.objects.filter(id = bid , book_type = "Free").exists()
        else:
          #not bought
          bought = True

        if bought :
          #check if user have review this book
          hadreview = Review.objects.filter(user_id=request.user.id,book_id=bid).all()
          hadreview = '' if len(hadreview) == 0 else hadreview[0]
    except Exception as e:
      print("Error in bookDescription :"+str(e))
      messages.error(request,"Internal Servre Error.")
  else:
    #no book found of that id
    messages.error(request,"Book Not Found.")
    return redirect('ReadBook:premiumbook')
  
  return render(request,'ReadBook/BookDescription.html',context={
    'book':book,
    'reviews':reviews,
    "loggedin":loggedin,
    "bought":bought,
    "hadreview":hadreview,
    "owner":owner,
    "amount":amount
    })

@login_required(login_url='/login/')
def review(request,bid):
  '''
    This view function will accept only post request and handle review of a particular book
  '''
  review = None
  user = None
  if request.method == "POST":
    #METHOD POST
    if Book.objects.filter(id = bid).exists():
      try:
        review = request.POST.get('review','').strip()
        user = request.user
        #checking if book has been bought or not or Free or Owned by user
        if (Transaction.objects.filter(user_id=user.id,book_id=bid).exists()) or (Book.objects.filter(id = bid , book_type = "Free").exists()) or (Book.objects.get(pk = bid).uploaded_by_id == request.user.id):

          if review == '' :
            raise Exception('Review is Null')
          elif Review.objects.filter(user_id = user.id , book_id = bid).exists():
            #update existing Review
            update_row = Review.objects.filter(user_id = user.id , book_id = bid).get()
            update_row.review = review
            update_row.save()
          else:
            #create new Review
            Review.objects.create(book_id = bid , user_id = user.id, review = review)

          messages.success(request,"Review added successfully")
          return redirect("ReadBook:description", bid=bid)

        else:
          #book not bought
          messages.error(request,"You must buy this book to Review this book.")
          return redirect("ReadBook:description", bid=bid)
      except Exception as e:
        print("Error in review :"+str(e))
        messages.error(request, 'Error while adding review')
        return redirect("ReadBook:description", bid=bid)
    else:
      # if No Book
      messages.error(request,"Internal Server Error")
      return redirect("ReadBook:premiumbook")
  else:
    #METHOD GET
    #No page for get method
    messages.error(request,"Page Not Found")
    return redirect("ReadBook:premiumbook")

@login_required(login_url='/login/')
def rating(request,bid):
  '''
    This view function will accept only post request and handle Rating of a particular book
  '''
  rating = None
  user = None
  if request.method == "POST":
    #METHOD POST
    if Book.objects.filter(id = bid).exists():
      try:
        rating = int(request.POST.get('star',None))
        user = request.user
        #checking if book has been bought or not or Free or own by Author itself
        if (Transaction.objects.filter(user_id=user.id,book_id=bid).exists()) or (Book.objects.filter(id = bid , book_type = "Free").exists()) or (Book.objects.get(pk = bid).uploaded_by_id == request.user.id): 

          if rating > 5 or rating < 1 :
            raise Exception('Rating Not valid')
          elif Review.objects.filter(user_id = user.id , book_id = bid).exists():
            #update existing rating
            update_row = Review.objects.filter(user_id = user.id , book_id = bid).get()
            update_row.rating = rating
            update_row.save()
            #calling function that make change in book_rating cell
            calculateRating(bid)
          else:
            #create new one
            Review.objects.create(book_id = bid , user_id = user.id, rating = rating)
            calculateRating(bid)
          messages.success(request,"Rating added successfully")
          return redirect("ReadBook:description", bid=bid)

        else:
          #book not bought
          messages.error(request,"You must buy this book to Rate this book.")
          return redirect("ReadBook:description", bid=bid)
      except Exception as e:
        print("Error in rating :"+str(e))
        messages.error(request, 'Error while adding your rating')
        return redirect("ReadBook:description", bid=bid)
    else:
      # If No Book
      messages.error(request,"Internal Server Error")
      return redirect("ReadBook:premiumbook")
  else:
    #METHOD GET
    #No page for get method
    messages.error(request,"Page Not Found")
    return redirect("ReadBook:premiumbook")

@login_required(login_url='/login/')
@author_only
def addBook(request):
  '''
    This view function will handle both post and get method for adding book.
    This function is only allowed to access if user type is author and user is logged in 
  '''
  name = ''
  price = ''
  btype = ''
  cover = ''
  pdf = ''
  description=''
  category=''
  userid=''
  if request.method == 'POST':
    #Method POST
    try:
      name = request.POST['name'].strip()
      btype = request.POST['type'].strip()
      description = request.POST['description'].strip()
      category = request.POST['category'].strip()
      cover = request.FILES.get('image',None)
      pdf = request.FILES['file']
      userid = request.user.id

      #checking book type
      if btype != 'Free':
        price = int(request.POST['price'])
      else:
        price = 0

      #checking for errors
      if (name == '' or btype == '' or description == '' or category == ''):
        raise Exception('Empty Field')
      elif pdf.content_type != 'application/pdf':
        raise Exception('File Type Error')
      elif cover == None:
        cover = 'book_images\\no_cover.jpg'
      elif cover.content_type != 'image/jpeg' and cover.content_type != 'image/png':
        raise Exception('Image Type Error')
      
      Book.objects.create(book_name=name,book_price=price ,book_type=btype,book_cover=cover,book_description=description,book_category=category,book_file=pdf,uploaded_by_id=userid)

      #success 
      messages.success(request,"Book Added Successfully.")
      return redirect('ReadBook:premiumbook')
    except Exception as e:
      print("ERROR : "+str(e))
      messages.error(request,"Error while processing the data. This might be because data is incorrect.")

  return render(request,'ReadBook/AddBook.html',context={
    'bookname':name,
    'bookprice':price,
    'description':description,
    'category':category
    })

@login_required(login_url='/login/')
@author_only
def updateBook(request,bid):
  '''
    This view function will handle both post and get method for updating book.
    This function is only allowed to access if user type is author and user is logged in 
  '''
  if Book.objects.filter(id = bid):
    book = Book.objects.get(id = bid)
    if request.method == 'POST':
      #METHOD POST
      try:
        name = request.POST['name'].strip()
        btype = request.POST['type'].strip()
        description = request.POST['description'].strip()
        category = request.POST['category'].strip()
        userid = request.user.id

        if book.uploaded_by_id == userid:
          #checking book type
          if btype != 'Free':
            price = int(request.POST['price'])
          else:
            price = 0

          #checking for errors
          if (name == '' or btype == '' or description == '' or category == ''):
            raise Exception('Empty Field')

          #updating Book
          book.book_name=name
          book.book_price=price
          book.book_type=btype
          book.book_description=description
          book.book_category=category
          book.save()

          #success
          messages.success(request,"Book updated Successfully")
          return redirect('ReadBook:description',bid=book.pk)
        else:
          # not the same user
          messages.error(request,"You do not have permission to Update book.")
          return redirect("ReadBook:description", bid=book.pk)
      except Exception as e:
        print("ERROR : "+str(e))
        messages.error(request,"Error while processing the data. This might be because data is incorrect.")
        return redirect("ReadBook:description", bid=book.pk)
    else:

templates/ReadBook/Book.html
{% extends 'Base/Header.html' %} {% block content %} {% load static %}
<div class="row">
  {% if not books %}
  <h3 align="center" style="color:#9e9e9e">No books to display</h3>
  {% else %}
  <!-- error displayig area -->
  {% if messages %} {% for message in messages %}
  <div {% if message.tags %} class="{{ message.tags }} alert-danger" {% endif %} id="alert">
    {{ message }}
    <i class="material-icons" style="color:black; float:right; cursor: pointer;" id="closealert">
      close
    </i>
  </div>
  {% endfor %} {% endif %}
  <!-- end error displaying area -->
  {% for book in books %}
  <div class="col s6 m5 l4">
    <div class="card">
      <div class="card-image">
        <a href="{% url 'ReadBook:description' book.id %}" style="color: white;">
          <img src="{{book.book_cover.url}}" style="height:290px;border: 1px solid #9e9e9e; padding: 5px;" />
        </a>
      </div>
      <div
        class="card-content"
        style=" overflow: hidden; 
        border-top: 1px solid rgba(113, 112, 112, 0.3); padding: 0px;"
      >
        <div style="background: #26a69a;padding: 2px 13px;">
          <a href="{% url 'ReadBook:description' book.id %}" style="color: white;">
            <span class="card-title">{{book.book_name|title}}</span>
          </a>
        </div>
      </div>
      <div class="card-action" style="display: flex;align-items: baseline;">
        <div>
          <span style="font-size: 17px;">
            Rating: {{book.book_rating}}
          </span>
          <i class="material-icons" style="vertical-align: text-bottom;">
            star_half
          </i>
          <!-- new indication for new books -->
          <!-- <span style="color:#ec1e24">
            <sup style="vertical-align: text-top;">New</sup>
          </span> -->
        </div>
        <div style="margin-left: auto;">
          <a href="{% url 'ReadBook:description' book.id %}" class="btn waves-effect">
            {{ book.book_price|yesno:'$,Free' }}{% firstof book.book_price %} {{ book.book_discount|yesno:'-,' }} {% firstof book.book_discount %}{{book.book_discount|yesno:'%,' }}
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %} {% endif %}
</div>
{% endblock %}

templates/ReadBook/BookDescription.html
{% extends 'Base/Header.html' %} {% block content %}
<!-- error displayig area -->
{% if messages %} {% for message in messages %}
<div {% if message.tags %} class="{{ message.tags }} alert-danger" {% endif %} id="alert">
  {{ message }}
  <i class="material-icons" style="color:black; float:right; cursor: pointer;" id="closealert">
    close
  </i>
</div>
{% endfor %} {% endif %}
<!-- end error displaying area -->
<div class="row" style="border:1px solid #9e9e9e; margin-bottom:0px">
  <div style="padding:0px 10px">
    <div class="row" style="margin-bottom:5px; border-bottom: 1px solid #e0e0e0;">
      <div class="col m7 s12">
        <h3 style="margin-top: 5px; margin-bottom: 0.8rem; padding-left: 20px;">
          {{book.book_name|title}}
        </h3>
      </div>
      <div class="col m5 s12" style="display: flex; justify-content: right;">
        <p style="display: none;" id="ratingvalue">{{book.book_rating}}</p>
        <!-- to show total book rating from js -->
        <div id="totalrating" style="position: relative; top: 30%;"></div>
      </div>
    </div>
  </div>
  <div class="row">
    <!-- image section -->
    <div class="col s12 l3 m4">
      <div style="padding:5px; border: 1px solid black;" align="center">
        <img src="{{book.book_cover.url}}" alt="{{book.book_name}}" class="img-fluid" style="height: 250px;vertical-align: bottom" />
      </div>
      <div>
        <form method="POST" id="ratingform" action="{% url 'ReadBook:rating' book.pk %}">
          {% csrf_token %}
          <div class="rating">
            <!-- to display logged in user rating  -->
            {% if loggedin and bought %}
            <input type="radio" name="star" id="star1" value="5" />
            <label for="star1"></label>
            <input type="radio" name="star" id="star2" value="4" />
            <label for="star2"></label>
            <input type="radio" name="star" id="star3" value="3" />
            <label for="star3"></label>
            <input type="radio" name="star" id="star4" value="2" />
            <label for="star4"></label>
            <input type="radio" name="star" id="star5" value="1" />
            <label for="star5"></label>
            <input type="hidden" id="current_user_rating" value="{{hadreview.rating|yesno:',0'}}{% firstof hadreview.rating %}" />
            {% else%}
            <input type="radio" name="star" id="star1" value="5" disabled />
            <label for="star1"></label>
            <input type="radio" name="star" id="star2" value="4" disabled />
            <label for="star2"></label>
            <input type="radio" name="star" id="star3" value="3" disabled />
            <label for="star3"></label>
            <input type="radio" name="star" id="star4" value="2" disabled />
            <label for="star4"></label>
            <input type="radio" name="star" id="star5" value="1" disabled />
            <label for="star5"></label>
            {% endif %}
          </div>
        </form>
      </div>

      {% if not book.book_price %}
      <!-- free -->
      <a href="{{ book.book_file.url }}" class="btn waves-effect" style="width:100%" target="_blank"><i class="material-icons" style="vertical-align: inherit;"> chrome_reader_mode</i> Free </a>
      {% elif not bought or not loggedin %}
      <!-- buy -->
      <div style="margin: 10px;">
        <form action="{% url 'Payment:getBook' book.pk %}" method="POST">
          {% csrf_token %}
          <button class="btn waves-effect" type="submit" style="width:100%">
            ${{book.book_price}} {{ book.book_discount|yesno:'-,' }} {% firstof book.book_discount %}{{book.book_discount|yesno:'%,' }}
          </button>
        </form>
      </div>
      {% elif loggedin and bought %}
      <!-- bought -->
      <div style="margin: 10px;">
        <a href="{% url 'ReadBook:download' book.pk %}" class="btn waves-effect" style="width:100%" target="_blank"
          ><i class="material-icons" style="vertical-align: inherit;"> file_download</i> DOWNLOAD</a
        >
      </div>
      {% endif %}
    </div>
    <!-- image section ends -->

    <!-- description section -->
    <div class="col s12 m6 l7">
      <div class="" style="height:0px; min-height: 367px; margin-bottom: 13px; padding: 10px; border-bottom: 1px solid #8a8a8a82; overflow: hidden;">
        <h6 style="margin-top: 5px; font-weight: 501; display: inline-block;">
          Description:
        </h6>
        <i class="material-icons b_description_down">keyboard_arrow_down</i>
        <p style="text-align: justify; margin:5px 0px;">
          &emsp;{{book.book_description}}
        </p>
      </div>
    </div>
    <!-- description section ends -->

    <div class="col s12 m2 l2" align="center">
      {% if owner %}
      <div style="margin-top: 20px;">
        <form method="POST" action="{% url 'ReadBook:deletebook' book.pk %}">
          {% csrf_token %}
          <button class="waves-effect waves-light btn" type="submit" style="width: 100%;">Delete<i class="material-icons right">delete_forever</i></button>
        </form>
      </div>

      <div style="margin-top: 20px;">
        <form method="GET" action="{% url 'ReadBook:updateBook' book.pk %}">
          <button class="waves-effect waves-light btn" type="submit" style="width: 100%;">Update<i class="material-icons right">update</i></button>
        </form>
      </div>
      {% endif %}
    </div>
    <!-- review section -->
    <div class="row" style="margin-bottom: 0px;">
      <div class="col s12 l7 offset-l3">
        <div style="box-shadow: 0px 0px 3px #404040; padding-bottom: 0.5px; padding-top: 0.5px;">
          <!-- review form -->
          <form method="POST" id="reviewform" action="{% url 'ReadBook:review' book.pk %}">
            {% csrf_token %}
            <div class="row" style="padding-left:7px; margin-bottom: 0px;">
              {% if loggedin and bought %}
              <div class="input-field col s10 l10" style="margin-bottom: 0px;">
                <textarea name="review" id="review" class="materialize-textarea" data-length="200" required>{{hadreview.review}}</textarea>
                <label for="review">Review</label>
              </div>
              <div class="input-field col s2 l2" style="text-align: center; margin-bottom: 0px;">
                <button type="submit" class="btn waves-effect">
                  <i class="material-icons">rate_review</i>
                </button>
              </div>
              {% else %}
              <div class="input-field col s10 l10" style="margin-bottom: 0px;">
                <textarea name="review" id="review" class="materialize-textarea" data-length="200" required disabled></textarea>
                <label for="review">You haven't bought the book</label>
              </div>
              <div class="input-field col s2 l2" style="text-align: center; margin-bottom: 0px;">
                <button type="submit" class="btn waves-effect" disabled>
                  <i class="material-icons">rate_review</i>
                </button>
              </div>
              {% endif %}
            </div>
          </form>

          <!-- loggedin user review -->
          {% if hadreview %}
          <div class="row" style="margin:10px 0px 5px 0px; border: 1px solid #bbb;">
            <div class="col l2" style="text-align:center;">
              <i class="material-icons" style="font-size: 5rem;margin-left: -5px;">account_circle</i>
            </div>
            <div class="col l10" style="overflow: hidden; border-left: 1px solid #bbb;">
              <h6 style="display: inline-block; margin-top: 5px; font-weight: 501;">
                {{hadreview.user.users.username|title}}
              </h6>
              <span style="font-weight: 501;">
                | Rating: <span id="userrating">{{hadreview.rating}}</span>
                <i class="material-icons" style="vertical-align: text-bottom;">
                  star_half
                </i>
              </span>
              <i class="material-icons" id="b_edit_review">mode_edit</i>
              <i class="material-icons b_review_down">keyboard_arrow_down</i>
              <p style="margin:0px; margin-bottom:10px; text-align: justify; min-height: 39px; height:0px">
                {{hadreview.review}}
              </p>
            </div>
          </div>
          {% endif %}

          <!-- loggedin user review ends -->

          <!-- review block -->
          {% for review in reviews %} {% if review.user_id != hadreview.user_id %}
          <div class="row" style="margin:10px 0px 5px 0px; border: 1px solid #bbb;">
            <div class="col l2" style="text-align:center;">
              <i class="material-icons" style="font-size: 5rem;margin-left: -5px;">account_circle</i>
            </div>
            <div class="col l10" style="overflow: hidden; border-left: 1px solid #bbb;">
              <h6 style="display: inline-block; margin-top: 5px; font-weight: 501;">
                {{review.user.users.username|title}}
              </h6>
              <span style="font-weight: 501;">
                | Rating: <span id="userrating">{{review.rating}}</span>
                <i class="material-icons" style="vertical-align: text-bottom;">
                  star_half
                </i>
              </span>
              <i class="material-icons b_review_down">keyboard_arrow_down</i>
              <p style="margin:0px; margin-bottom:10px; text-align: justify; min-height: 39px; height:0px">
                {{review.review}}
              </p>
            </div>
          </div>
          {% endif %} {% endfor %}
          <!-- review block ends -->
        </div>
      </div>
    </div>
    <!-- review section ends -->
  </div>
</div>
<script>
  // showing rating in top right
  $(document).ready(function() {
    val = $("#ratingvalue").text();
    for (number = 0; number < val; number++) {
      $("#totalrating").append('<i class="material-icons b_bookrating">\
            star\
        </i>');
    }
    for (number = 0; number < 5 - val; number++) {
      $("#totalrating").append('<i class="material-icons b_bookrating" style="color:black;">\
            star_border\
        </i>');
    }
    //to make total rating center of div
    t = $("#totalrating").css("top");
    $("#totalrating").css("top", t);
  });

  //character count from materialize
  $(document).ready(function() {
    $("#review").characterCounter();
  });

  // review show more icon
  $(document).ready(function() {
    $(".b_review_down").click(function() {
      if ($(this).text() == "keyboard_arrow_down") {
        $(this).text("keyboard_arrow_up");
        $(this)
          .next()
          .css("height", "unset");
      } else {
        $(this).text("keyboard_arrow_down");
        $(this)
          .next()
          .css("height", "0px");
      }
    });
  });

  // description show more icon
  $(document).ready(function() {
    $(".b_description_down").click(function() {
      if ($(this).text() == "keyboard_arrow_down") {
        $(this).text("keyboard_arrow_up");
        $(this)
          .parent()
          .css("height", "unset");
      } else {
        $(this).text("keyboard_arrow_down");
        $(this)
          .parent()
          .css("height", "0px");
      }
    });
  });

  //submiting rating form
  $(document).ready(function() {
    $("#ratingform input").click(function() {
      $("#ratingform").submit();
    });
  });

  //setting user rating
  $(document).ready(function() {
    if (document.getElementById("star1").hasAttribute("disabled") == false) {
      var v = $("#current_user_rating").val();
      var stars = $('input[name="star"]');
      for (star of stars) {
        if ($(star).val() == v) {
          $(star).prop("checked", true);
        }
      }
    }
  });

  // to hide and show the review form.
  $(document).ready(function() {
    //checking if icon exists or not
    if ($("#b_edit_review").length == 1) {
      $("#reviewform").slideUp();
    }

    $("#b_edit_review").click(function() {
      if ($(this).text() == "mode_edit") {
        $(this).text("close");
        $("#reviewform").slideDown();
      } else if ($(this).text() == "close") {
        $(this).text("mode_edit");
        $("#reviewform").slideUp();
      }
    });
  });
</script>
{% endblock %}