Elibrary/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #add include to your apps url.py
    path('',include('ReadBook.urls')),
    path('',include('Payment.urls')),
    path('',include('Search.urls')),
    path('', include('Accounts.urls')),
    path('api/',include('GET_API.urls')),
    path('api/',include('DELETE_API.urls')),
    path('api/',include('PUT_API.urls')),
    path('api/',include('POST_API.urls')),
    path('api/',include('PostBook_POST_API.urls')),
]

Payment/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'Payment'

urlpatterns = [
	path('getbook/<int:id>', views.getBook, name= 'getBook'),
	path('payment/<int:bid>', views.payment, name ='Payment'),
	path('updateamount/', views.update_amount, name ='updateamount'),
]

Search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name= 'Search'
urlpatterns = [
	path('search/', views.search, name='search'),
]

Payment/models.py
from django.db import models

# Create your models here.

Search/models.py
from django.db import models

# Create your models here.

Payment/views.py
from django.shortcuts import render,redirect
from ReadBook.models import UserInfo, Book, Transaction
from django.contrib.auth.decorators import login_required

# Get book information from Book app and calculate total book price by giving or not giving discount
@login_required(login_url = '/login/')
def getBook(request,id):
	if Book.objects.filter(id=id).exists():
		book = Book.objects.get(id=id)
		dis = (int (book.book_discount) * int(book.book_price))/100
		total = book.book_price - dis
		return render(request,'Payment/transaction.html', context={'book':book, 'total': total})
	else:
		return redirect('ReadBook:premiumbook')

# This function payment() is for making transaction by the reader for premiun books.
@login_required(login_url = '/login/')  
def payment(request,bid):
	reader = request.user
	userinfo = UserInfo.objects.filter(id = reader.id).get()
	if request.method == 'POST':
		if Book.objects.filter(id = bid).exists():
			book=Book.objects.get(id = bid) 
			author=book.uploaded_by
			dis = (int (book.book_discount) * int(book.book_price))/100
			total = book.book_price - dis
			# This condition is for checking the user amount with the total amount of book.
			if userinfo.user_amount>=total:   
				pay=(int(userinfo.user_amount))-(int(total))	
				userinfo.user_amount=pay
				userinfo.save()

				# If the user amount is greate or equal to books price then 60% of total book price will be added in book uploader account.
				amou = (int(total) * 60)/100
				author.user_amount = int(author.user_amount) + amou
				author.save()

				# This query creates transaction by deducting amount from reader and adding amount in book uploader.
				Transaction.objects.create(user_id=userinfo.id, price=book.book_price, discount=book.book_discount, book_id=bid,total = total)
				# After successful transaction, user is redirect to homepage
				return redirect('ReadBook:description', bid = bid)

				#If the user amount is less than total book price then error message is displayed to the user.
			elif userinfo.user_amount<total:
				#add django message
				return redirect('Payment:updateamount')
		else:
			#if no book
			return redirect('ReadBook:premiumbook')
	else:
		return redirect('Payment:getBook',id=bid)

# This function is for updating the user amount incase of not sufficient amount available for purchasing book 
@login_required(login_url = '/login/')
def update_amount(request):
	if request.method == 'POST':
		user = request.user
		userinfo = UserInfo.objects.filter(users_id =user.id).get()
		amount = request.POST.get('amount',0)
		userinfo.user_amount = int(userinfo.user_amount)+int(amount)
		userinfo.save()
		return redirect('ReadBook:premiumbook')

	return render(request, 'Payment/updateprice.html')
	


	

Search/views.py
from django.shortcuts import render
from ReadBook.models import Book
from django.db.models import Q

# This function get the book objects and render the object in search.html templates
def search(request):
	query =""
	book = ''
	if request.GET:
		query = request.GET.get('q','').strip()		
		if query != '':
			book = get_data_queryset(query)
	return render(request, 'ReadBook/Book.html',context={"books": book})

#This function will return data and set() will remove repetition of output data and list() is for typecasting
def get_data_queryset(query= None):
	queryset = [] 
	queries = query.split(" ") 
	for q in queries:
		books = Book.objects.filter(
			Q(book_name__icontains= q)
			).distinct()
		for book in books:
			queryset.append(book)
	return list(set(queryset))

templates/Payment/search.html
{% extends 'Base/header.html' %}
{% block content %}
<form method="get" class="search-bar">
	<input type="text" class="form-control" name="q" placeholder="Search" id="id_b">
</form>
{% if books %}
<table class="table">
	<thead>

	<tbody>
		{% for book in books %}
		<tr>
			<td>{{book.book_name}}</td>
			<td>{{book.book_file}}</td>
		</tr>
	</tbody>
	</thead>
	{% endfor %}
</table>
{% else %}
<div class="container">
	<div class="row">
		<div class="card-body">
			<h1 class="card-title">No Result</h1>

		</div>
	</div>
</div>
{% endif %}
<script type="text/javascript">
	document.getElementbyId('id_b').value = "{{query}}"
</script>
{% endblock %}

templates/Payment/transaction.html
{% extends 'Base/Header.html'%}
{% block content %}

{% load static %}
<div class="section"></div>
<div style="background-image: url('{% static 'Payment/image.png.jpg' %}');">
  <div id="flayer" style="margin-left:50px;">
    <div id="slayer">
      <div class="container" id="content">
        <div class="row">
          <div class="col l3 m3 s12"></div>
          <div class="col l6 m6 s12">
            {% if error %}
            <div class="s-alert-danger">
              {{error}}
            </div>
            {% endif %}
            <form action="{% url 'Payment:Payment' book.pk %}" method="POST">
              {% csrf_token %}
              <div class="card-panel z-depth-5">
                <img src="{% static 'Payment/logo.jpg' %}" alt="" class="s_responsive">
                <div class="sidebar">
                  <div class="sidebar-text">
  
                    <div class="input-field">
                      <i class="material-icons prefix">date_range</i>
                      <input type="text" name="date" class="sdate" id="nowdate" value="" disabled="">
                    </div>
  
                    <div class="input-field">
                      <i class="material-icons prefix">account_circle</i>
                      <input type="text" name="username" class="suser" value="{{book.uploaded_by}}" disabled="">
                      <label>Username</label>
                    </div>
  
                    <div class="input-field">
                      <i class="material-icons prefix">book</i>
                      <input type="text" name="book" class="sbook" value="{{book.book_name}}" disabled="">
                      <label>Book</label>
                    </div>
                    <div class="input-field">
                      <i class="material-icons prefix">payment</i>
                      <input type="text" name="price" class="sprice" value="{{book.book_price}}" disabled="">
                      <label>Price</label>
                    </div>
                    <div class="input-field">
                      <i class="material-icons prefix">payment</i>
                      <input type="text" name="discount" class="sdiscount" value="{{book.book_discount}}%" disabled="">
                      <label>Discount</label>
                    </div>
  
                    <div class="input-field">
                      <i class="material-icons prefix">payment</i>
                      <input type="text" name="total" class="sfinalpayment" value="{{total}}" disabled="">
                      <label>Final Payment</label>
                    </div>
  
                    <input type="submit" name="submit" value="Conform Payment" class="btn left col s12">
  
                    <div class="clearfix"></div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  const login = document.querySelectorAll(".modal");
  M.Modal.init(login, {
    opacity: 0.7,
    dismissible: false
  });

  document.querySelector("#content").style.display = "none";
  document.querySelector("#flayer").classList.add("s_progress");
  document.querySelector("#slayer").classList.add("indeterminate");

  setTimeout(function () {
    document.querySelector("#flayer").classList.remove("s_progress");
    document.querySelector("#slayer").classList.remove("indeterminate");
    document.querySelector("#content").style.display = "block";
  }, 500)

  $(document).ready(function (){
    var today = new Date();
    var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
    $("#nowdate").val(date);
  })
</script>

</body>


</html>

{% endblock %}

templates/Payment/updateprice.html
{% extends 'Base/Header.html'%}
{% block content %}
<div class="section"></div>
<center>
	<div class="container">
		<div class="z-depth-1 grey lighten-4 row"
			style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE; margin-left: -650px;">
			<form class="col s12" action="{% url 'Payment:updateamount'%}" method="post">

				<div class='row'>
					<div class='col s12'>
					</div>
				</div>
				{% csrf_token %}
				<div class='row'>
					<div class='input-field col s12'>
						<input class='validate' type='text' name='password' id='password' />
						<label for='password'>CardNumber</label>
					</div>

					<div class='row'>
						<div class='input-field col s12'>
							<input class='validate' type='text' name='amount' id='password' />
							<label for='password'>Amount</label>
						</div>

						<center>
							<div class='row'>
								<button type='submit' name='btn_login'
									class='col s12 btn btn-large waves-effect indigo'>Update Amount</button>
							</div>
						</center>
					</div>
				</div>
			</form>
		</div>
	</div>
</center>
{% endblock %}